#ifndef __MY_BOARD_CONFIG_H__
#define __MY_BOARD_CONFIG_H__

// TODO different board revs
#define CONFIG_MXC_UART_BASE UART2_BASE

#include "mx5_common.h"
#include <asm/arch/imx-regs.h>


#define CONFIG_SYS_FSL_ESDHC_ADDR 0

#define PHYS_SDRAM_1 CSD0_BASE_ADDR
// TODO: different sdram sizes
#define PHYS_SDRAM_1_SIZE	(256 * 1024 * 1024)
#define CONFIG_SYS_SDRAM_BASE PHYS_SDRAM_1
#define CONFIG_SYS_INIT_RAM_ADDR IRAM_BASE_ADDR
#define CONFIG_SYS_INIT_RAM_SIZE IRAM_SIZE
#define CONFIG_SYS_INIT_SP_OFFSET (CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)
#define CONFIG_SYS_INIT_SP_ADDR (CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)
#endif
